### ISSUE TITLE
Avoid negative yield stress values

### ISSUE THREAD

**Issue by laurentbugnard** [tdegeus/GooseEPM#19]
Maybe we should make sure that yield stress values are always positive, which might not be the case when sigmay_std is not negligible w.r.t. sigmay_mean.

https://github.com/tdegeus/GooseEPM/blob/586b883292fe7bca801e706cf7aea6f1fb8aa409/include/GooseEPM/System.h#L255-L257

The change should then also be made when resampling.

https://github.com/tdegeus/GooseEPM/blob/586b883292fe7bca801e706cf7aea6f1fb8aa409/include/GooseEPM/System.h#L623

What do you think?

**Comment by tdegeus** [comment]
Sounds programmatically fair. Technically this could always happen even if the standard deviation is small. I wonder, however, if the absolute value is the right thing to do. We could also truncate at zero?

**Comment by laurentbugnard** [comment]
You are right, I suggest we use a truncated normal distribution. It would be the most neutral choice, as our friend wikipedia says: "The truncated normal is the maximum entropy probability distribution for a fixed mean and variance, with the random variate X constrained to be in the interval [a,b]." Since prrng doesn't have this feature yet, we could implement it. Or we could find a workaround: intuitively, I would say that simply refusing negative values and resample them would give the same result.
